# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool: Default

stages:
- stage: Build
  displayName: Build & Code Quality
  jobs:
  - job: BuildPythonApp
    displayName:  Build Python Application
    steps:  
    
    - task: PowerShell@2
      displayName: Check Python Version & Install Lint Tool
      inputs:
        targetType: 'inline'
        script: |
          python --version
          python -m pip install --upgrade pip
          python -m pip install ruff
          python -m ruff --version


    - task: PowerShell@2
      displayName: Run Python Linting (Ruff)
      inputs:
        targetType: 'inline'
        script: |
          python -m ruff check --fix .


    - task: PublishPipelineArtifact@1
      displayName: Publish Application Artifact
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/app.py'
        artifact: 'vivek-todo'
        publishLocation: 'pipeline'




