# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool: Default

stages:
- stage: Build
  displayName: Build & Code Quality
  jobs:
  - job: BuildPythonApp
    displayName: Build Python Application
    steps:

    - checkout: self

    - task: PowerShell@2
      displayName: Check Python Version & Install Lint Tool
      inputs:
        targetType: 'inline'
        script: |
          python --version
          python -m pip install --upgrade pip
          python -m pip install ruff
          python -m ruff --version

    - task: PowerShell@2
      displayName: Run Python Linting (Ruff)
      inputs:
        targetType: 'inline'
        script: |
          python -m ruff check --fix "$(Build.SourcesDirectory)/PyTodoBackendMonolith/app.py"

    - task: PublishPipelineArtifact@1
      displayName: Publish Application Artifact
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/app.py'
        artifact: 'vivek-todo'
        publishLocation: 'pipeline'

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'vivek-todo'
        targetPath: '$(Pipeline.Workspace)/vivek-todo'


    # - task: ArchiveFiles@2
    #   inputs:
    #     rootFolderOrFile: '$(Pipeline.Workspace)/todoapi_artifact'
    #     includeRootFolder: true
    #     archiveType: 'zip'
    #     archiveFile: '$(Build.ArtifactStagingDirectory)/artifact.zip'
    #     replaceExistingArchive: true








