# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool: Default

stages:
- stage: Build
  displayName: Build & Code Quality
  jobs:
  - job: BuildPythonApp
    displayName:  Build Python Application
    steps:  
    
    - task: PowerShell@2
      displayName: Check Python Version & Install Lint Tool
      inputs:
        targetType: 'inline'
        script: |
          python --version
          pip install ruff


    - task: PowerShell@2
      displayName: Run Python Linting (Ruff)
      inputs:
        targetType: 'inline'
        script: 'ruff check --fix .'


    - task: PublishPipelineArtifact@1
      displayName: Publish Application Artifact
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/app.py'
        artifact: 'vivek-todo'
        publishLocation: 'pipeline'


#     - task: DownloadPipelineArtifact@2
#       inputs:
#         buildType: 'current'
#         artifactName: 'todoapi_artifact'
#         targetPath: '$(Pipeline.Workspace)/todoapi_artifact'


#     - task: ArchiveFiles@2
#       inputs:
#         rootFolderOrFile: '$(Pipeline.Workspace)/todoapi_artifact'
#         includeRootFolder: true
#         archiveType: 'zip'
#         archiveFile: '$(Build.ArtifactStagingDirectory)/artifact.zip'
#         replaceExistingArchive: true


# - stage: Deploy
#   displayName: Deploy Application to VM
#   dependsOn: Build
#   jobs:
#   - deployment: deployPy
#     environment: 
#       name: python
#       # resourceName: python-vm
#       resourceType: virtualMachine
#     strategy:
#       runOnce:
#         deploy:
#           steps:


#           - task: DownloadPipelineArtifact@2
#             displayName: Download Build Artifact
#             inputs:
#               buildType: 'current'
#               artifactName: 'todoapi_artifact'
#               targetPath: '$(Pipeline.Workspace)'


#           - task: Bash@3
#             displayName: Stop Service, Deploy Code & Restart
#             inputs:
#               targetType: 'inline'
#               script: |
#                 sudo systemctl stop pytodo
                
#                 rm -rf /home/vm-sername01/todoapi/app.py
                
#                 rm -rf /home/vm-username01/todoapi/*.py
                
#                 rm -rf /home/vm-username01/todoapi/app/
                
#                 cp -r $(Pipeline.Workspace)/todoapi_artifact/* /home/vm-username01/todoapi/
                
#                 sudo systemctl start pytodo

#                 sudo nano /etc/systemd/system/uvicorn.service

#                 [Unit]
#                 Description=Todo API Uvicorn App
#                 After=network.target

#                 [Service]
#                 User=root
#                 WorkingDirectory=/home/usrname/todoapi
#                 ExecStart=/home/usrname/PyTodoBackendMonolith/venv/bin/uvicorn app:app --host 0.0.0.0 --port 8000
#                 Restart=always

#                 [Install]
#                 WantedBy=multi-user.target


#                 sudo systemctl daemon-reload
#                 sudo systemctl start uvicorn
#                 sudo systemctl status uvicorn
#                 sudo systemctl stop uvicorn




